services:
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/project/frontend
      - /project/frontend/node_modules
    ports:
      - "3000:3000"
    command: sh -c "bun dev"

  backend:
    build: ./backend
    volumes:
      - ./backend:/project/backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    command: sh -c "sh startup.sh"
